DevelopmentIntoMain
DariusDangi/fwf-api-poc-dispatcher pull request #1
Opened 2024-08-14 08:26 UTC by DariusDangi

Ready for first code review.

2024-08-14 09:33 UTC, RobertFWF commented on DataLayer/CreateOutputReport.xaml
Adauga si numele pentru sheet in Config.
Tabelul de Output se poate crea folosind Config-ul. Pui toate coloanele necesare in Config intr-un sir Nume;Email; ... si le adaugi pe rand intr-un tabel gol.

2024-08-14 09:38 UTC, RobertFWF commented on DataLayer/UploadQueueItem.xaml
Coloana de "Animal " poate fi in Config, iar totodata, ca sa creezi dictionarul pentru coada, poti pune coloanele de interes tot in Config (apoi mergi pe rand prin fiecare coloana de interes) sau daca ai nevoie de toate coloanele din TransactionItem atunci mergi pe rand prin coloane din TransactionItem si folosesti ColumnName [ dictQueueItem(column.ColumnName) = in_TransactionItem(column.ColumnName) ]

Numele coloanelor se mai schimba, de aici si problema cand sunt hardcoded.

2024-08-14 09:39 UTC, RobertFWF commented on Exceptions_Screenshots/ExceptionScreenshot_240812.035916.png
Sterge toate Screenshot-urile

2024-08-14 09:40 UTC, RobertFWF commented on Framework/CloseAllApplications.xaml
Nefolosit. Se poate sterge.

2024-08-14 09:41 UTC, RobertFWF commented on Framework/GetTransactionData.xaml
Daca nu folosesti field-urile suplimentare, poti sa le stergi. (Trebuie sa le stergi si din celelalte workflow-uri)

2024-08-14 09:42 UTC, RobertFWF commented on Framework/KillAllProcesses.xaml
Nefolosit.

2024-08-14 09:43 UTC, RobertFWF commented on Framework/SetTransactionStatus.xaml
Status pt BRE si SE sa fie BusinessException.Message/SystemException.Message

2024-08-14 09:50 UTC, RobertFWF commented on ServiceLayer/Outlook/Outlook_GetEmailList.xaml
Ai o activitate comentata. Poate fi stearsa daca nu o folosesti.

2024-08-14 09:51 UTC, RobertFWF commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
Invoke Code ar trebui pus intr-un Try Catch, iar pe catch exception facut un Log cu 'exceptio.InnerException.Message etc..." este in Best Practices cum ar trebui facut.

2024-08-14 09:53 UTC, RobertFWF reviewed
First Code Review

2024-08-20 07:02 UTC, FlorinBarsan requested changes
Please review those comments and ask for a re-review after you finished the implementation. Add a reply to each comment that you implemented and after all are done, ask for a re-review.

If you have any questions, feel free to pm me.

2024-08-20 07:02 UTC, FlorinBarsan commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
![image](https://github.com/user-attachments/assets/cdb3586d-c40e-4c08-954b-213127d20cbc)
add the necessary activities pls

2024-08-20 07:02 UTC, FlorinBarsan commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
> +        <Sequence sap:VirtualizedContainerService.HintSize="416,136" sap2010:WorkflowViewState.IdRef="Sequence_8">
redundant sequence

2024-08-20 07:02 UTC, FlorinBarsan commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
> +          <ui:GetOutlookMailMessages Filter="{x:Null}" FilterByMessageIds="{x:Null}" TimeoutMS="{x:Null}" Account="[in_Config(&quot;OutlookInputEmailAddress&quot;).ToString]" DisplayName="Get Mail Me
hardcoded mail folder

2024-08-20 07:02 UTC, FlorinBarsan commented on ServiceLayer/SendMailOnBRE.xaml
why this isn't in the Outlook subfolder? since you have service layer workflows only from one application, you can delete the folder and just leave the xaml files inside. Also you could add Outlook_ in the naming of this xaml

2024-08-20 07:02 UTC, FlorinBarsan commented on Main.xaml
redundant sequence in end process

2024-08-20 08:42 UTC, DariusDangi commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
Added Throw activity

2024-08-20 08:42 UTC, DariusDangi commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
> +        <Sequence sap:VirtualizedContainerService.HintSize="416,136" sap2010:WorkflowViewState.IdRef="Sequence_8">
removed the redundant sequence

2024-08-20 08:43 UTC, DariusDangi commented on ServiceLayer/Outlook/Outlook_GetMail.xaml
> +          <ui:GetOutlookMailMessages Filter="{x:Null}" FilterByMessageIds="{x:Null}" TimeoutMS="{x:Null}" Account="[in_Config(&quot;OutlookInputEmailAddress&quot;).ToString]" DisplayName="Get Mail Me
implemented using config file

2024-08-20 08:44 UTC, DariusDangi commented on ServiceLayer/SendMailOnBRE.xaml
removed unnecessary subfolder and renamed SendMailOnBRE workflow to Outlook_SendMailOnBRE

2024-08-20 08:44 UTC, DariusDangi commented on Main.xaml
removed redundant sequence

2024-08-20 08:55 UTC, FlorinBarsan approved these changes
good job!

2024-08-20 08:55 UTC, merged